### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by andybrandt** [alexbzg/DxClusterClient#1]
Tried to build it. Complies, but doesn't run because config files are missing in the repository (bandMap.txt & possibly others). 73 de SP9AB

**Comment by alexbzg** [comment]
Uploaded missing files. Put cty.dat, bandMap.txt, CountryCode.txt and lotw1.txt in compiled program folder.

**Comment by andybrandt** [comment]
Thanks. 
BTW - some other files appeared in the root directory of the solution:
14 Dec 2016  15:14           114,619 air_rafa.csv
14 Dec 2016  15:14           100,666 air_rafa1.csv
14 Dec 2016  15:14           798,898 rda.txt
14 Dec 2016  15:14           199,808 URDA.csv
14 Dec 2016  15:14            32,988 URDAlist.csv

Was this intentional?
